### PR TITLE
feat(custom) Custom post types, custom fields

### PR DESCRIPTION
**Pull request by ClaudiuCeia**
Custom post types:
- Proiecte, companii, etichete proiecte, statistici

Custom field types:
- Proiecte, companii, etichete proiecte, statistici

### CODE REVIEW

**Comment by cezarneaga** [comment]
Finally using trellis. If u master this i want to be your padawan

**Comment by ClaudiuCeia** [comment]
Well, it's not bad. If only we could find a way to use bedrock and trellis and develop the frontend on top of a WordPress GraphQL API...

**Comment by cezarneaga** [comment]
Pai se poate. Si inca cu gatsbyjs

**Comment by ClaudiuCeia** [comment]
Interesant, nu am folosit. Defapt nici macar nu prea sunt mare fan WordPress so there's that. O sa ma uit.

**Pull request merged**
